class_name EnemyTypes
extends RefCounted

const VC := "vc"
const FOUNDER := "founder"
const LAB_BOT := "lab_bot"
const MANAGER := "manager"
const INFLUENCER := "influencer"
const DELIVERY_BOT := "delivery_bot"
const BOARD_MEMBER := "board_member"
const DIRECTOR := "director"
const EXOSUIT := "exosuit"
const BOT_VOICE := "john"
const FEMALE_VOICE := "kristin"
const MALE_VOICE := "norman"

const CONFIGS := {
	"vc": {
		"display_name": "VENTURE CAPITALIST",
		"models": ["character-male-d.glb", "character-female-d.glb"],
		"model_folder": Models.CHARACTERS,
		"model_height": 1.75,
		"animations": {"idle": "idle", "move": "walk", "attack": "holding-right-shoot", "defeat": "emote-no", "exit": "walk"},
		"health": 60,
		"move_speed": 3.2,
		"min_range": 8.0,
		"max_range": 16.0,
		"attack": "throw",
		"attack_range": 24.0,
		"attack_cooldown": 1.9,
		"aim_error": 0.06,
		"damage": 2,
		"voice_pitch": 0.95,
		"defeat_line": "We'll pass.",
		"defeat_clip": "we_will_pass",
		"defeat_style": "walk_away",
	},
	"founder": {
		"display_name": "AI FOUNDER",
		"models": ["character-male-e.glb", "character-female-e.glb", "character-male-a.glb", "character-male-f.glb"],
		"model_folder": Models.CHARACTERS,
		"model_height": 1.7,
		"animations": {"idle": "idle", "move": "sprint", "attack": "attack-melee-right", "defeat": "emote-yes", "exit": "idle"},
		"health": 40,
		"move_speed": 5.0,
		"min_range": 0.0,
		"max_range": 0.0,
		"attack": "melee",
		"attack_range": 2.0,
		"attack_cooldown": 1.1,
		"aim_error": 0.0,
		"damage": 2,
		"voice_pitch": 1.08,
		"defeat_line": "Pivoting!",
		"defeat_clip": "pivoting",
		"defeat_style": "spin",
	},
	"lab_bot": {
		"display_name": "LAB SECURITY BOT",
		"models": ["RobotExpressive.glb"],
		"model_folder": "res://assets/models/robot/",
		"model_height": 1.9,
		"animations": {"idle": "Idle", "move": "Walking", "attack": "Punch", "defeat": "ThumbsUp", "exit": "ThumbsUp"},
		"health": 80,
		"move_speed": 2.6,
		"min_range": 6.0,
		"max_range": 13.0,
		"attack": "burst",
		"attack_range": 22.0,
		"attack_cooldown": 2.4,
		"aim_error": 0.04,
		"damage": 1,
		"voice_pitch": 1.3,
		"defeat_line": "Acqui-hired!",
		"defeat_clip": "acqui_hired",
		"defeat_style": "rise",
	},
	"manager": {
		"display_name": "SHIFT MANAGER",
		"models": ["character-male-b.glb", "character-female-b.glb"],
		"model_folder": Models.CHARACTERS,
		"model_height": 1.85,
		"animations": {"idle": "idle", "move": "walk", "attack": "attack-melee-right", "defeat": "emote-no", "exit": "walk"},
		"health": 130,
		"move_speed": 3.8,
		"min_range": 0.0,
		"max_range": 0.0,
		"attack": "melee",
		"attack_range": 2.2,
		"attack_cooldown": 1.4,
		"aim_error": 0.0,
		"damage": 3,
		"voice_pitch": 0.9,
		"defeat_line": "Let's take this offline.",
		"defeat_clip": "take_offline",
		"defeat_style": "walk_away",
	},
	"influencer": {
		"display_name": "THOUGHT LEADER",
		"models": ["character-female-a.glb", "character-male-c.glb", "character-female-c.glb"],
		"model_folder": Models.CHARACTERS,
		"model_height": 1.72,
		"animations": {"idle": "idle", "move": "walk", "attack": "holding-right-shoot", "defeat": "emote-yes", "exit": "walk"},
		"health": 50,
		"move_speed": 3.4,
		"min_range": 7.0,
		"max_range": 15.0,
		"attack": "fan",
		"fan_count": 3,
		"attack_range": 20.0,
		"attack_cooldown": 2.2,
		"aim_error": 0.05,
		"damage": 2,
		"voice_pitch": 1.05,
		"defeat_line": "Unsubscribing!",
		"defeat_clip": "unsubscribing",
		"defeat_style": "spin",
	},
	"delivery_bot": {
		"display_name": "DELIVERY BOT",
		"models": ["RobotExpressive.glb"],
		"model_folder": "res://assets/models/robot/",
		"model_height": 1.15,
		"collision_radius": 0.35,
		"collision_height": 1.2,
		"animations": {"idle": "Idle", "move": "Running", "attack": "Punch", "defeat": "ThumbsUp", "exit": "ThumbsUp"},
		"tint": Color(1.0, 0.45, 0.05, 0.28),
		"voice": "john",
		"health": 35,
		"move_speed": 6.2,
		"min_range": 0.0,
		"max_range": 0.0,
		"attack": "melee",
		"attack_range": 1.7,
		"attack_cooldown": 0.9,
		"aim_error": 0.0,
		"damage": 1,
		"voice_pitch": 1.6,
		"defeat_line": "Package delivered!",
		"defeat_clip": "package_delivered",
		"defeat_style": "rise",
	},
	"board_member": {
		"display_name": "LANCE UPROUND",
		"is_boss": true,
		"models": ["character-male-d.glb"],
		"model_folder": Models.CHARACTERS,
		"model_height": 3.4,
		"collision_radius": 0.85,
		"collision_height": 3.4,
		"animations": {"idle": "idle", "move": "walk", "attack": "holding-right-shoot", "defeat": "emote-no", "exit": "walk"},
		"tint": Color(0.25, 0.9, 0.3, 0.08),
		"voice": "norman",
		"health": 1100,
		"move_speed": 3.0,
		"min_range": 6.0,
		"max_range": 14.0,
		"attack": "throw",
		"boss_attacks": ["volley", "charge", "volley", "summon"],
		"volley_count": 5,
		"summon_types": ["vc", "influencer"],
		"summon_line": "Associates! Circle back on this!",
		"enrage_line": "This is a down round!",
		"stun_resistance": 0.3,
		"attack_range": 26.0,
		"attack_cooldown": 1.7,
		"aim_error": 0.05,
		"damage": 2,
		"voice_pitch": 0.9,
		"defeat_line": "Fine. You're in the round.",
		"defeat_clip": "youre_in_the_round",
		"defeat_style": "walk_away",
	},
	"director": {
		"display_name": "BOARD DIRECTOR",
		"is_boss": true,
		"models": ["character-male-f.glb", "character-female-f.glb", "character-female-d.glb"],
		"model_folder": Models.CHARACTERS,
		"model_height": 2.8,
		"collision_radius": 0.7,
		"collision_height": 2.8,
		"animations": {"idle": "idle", "move": "walk", "attack": "holding-right-shoot", "defeat": "emote-no", "exit": "walk"},
		"tint": Color(0.9, 0.7, 0.2, 0.1),
		"health": 650,
		"move_speed": 3.4,
		"min_range": 6.0,
		"max_range": 15.0,
		"attack": "throw",
		"boss_attacks": ["volley", "summon", "charge", "volley"],
		"volley_count": 4,
		"volley_color": Color(1.0, 0.85, 0.3),
		"volley_size": Vector3(0.3, 0.06, 0.3),
		"summon_types": ["manager", "influencer"],
		"summon_line": "Motion to summon security!",
		"enrage_line": "Point of order!",
		"stun_resistance": 0.35,
		"attack_range": 26.0,
		"attack_cooldown": 1.9,
		"aim_error": 0.05,
		"damage": 2,
		"voice_pitch": 0.95,
		"defeat_line": "This meeting is adjourned!",
		"defeat_clip": "meeting_adjourned",
		"defeat_style": "walk_away",
	},
	"exosuit": {
		"display_name": "PRESTON EXITWELL - EXOSUIT",
		"is_boss": true,
		"models": ["RobotExpressive.glb"],
		"model_folder": "res://assets/models/robot/",
		"model_height": 5.6,
		"collision_radius": 1.3,
		"collision_height": 5.2,
		"animations": {"idle": "Idle", "move": "Walking", "attack": "Punch", "defeat": "ThumbsUp", "exit": "ThumbsUp"},
		"tint": Color(1.0, 0.72, 0.15, 0.3),
		"voice": "norman",
		"health": 2600,
		"move_speed": 2.6,
		"min_range": 8.0,
		"max_range": 18.0,
		"attack": "burst",
		"boss_attacks": ["burst", "volley", "slam", "summon", "burst", "charge"],
		"volley_count": 6,
		"volley_color": Color(1.0, 0.82, 0.25),
		"volley_size": Vector3(0.32, 0.08, 0.32),
		"slam_damage": 4,
		"summon_types": ["delivery_bot", "lab_bot"],
		"summon_line": "Deploying the workforce!",
		"enrage_line": "Do you know how much this suit cost?!",
		"stun_resistance": 0.2,
		"attack_range": 30.0,
		"attack_cooldown": 1.5,
		"aim_error": 0.04,
		"damage": 2,
		"voice_pitch": 0.85,
		"defeat_line": "Okay! Okay! Everybody gets a ladder!",
		"defeat_clip": "everybody_gets_a_ladder",
		"defeat_style": "rise",
	},
}


static func is_boss(type_id: String) -> bool:
	return CONFIGS[type_id].get("is_boss", false)


static func pick_voice(type_id: String, model_file: String) -> String:
	var config: Dictionary = CONFIGS[type_id]
	if config.has("voice"):
		return config["voice"]
	if type_id == LAB_BOT:
		return BOT_VOICE
	if model_file.contains("female"):
		return FEMALE_VOICE
	return MALE_VOICE
