class_name RustSlop
extends Label3D

const WORLD_LAYER := 1
const GRAVITY := 7.0
const AIR_DRAG := 0.8
const LIFETIME_SECONDS := 8.0
const FADE_SECONDS := 1.5
const FONT_SIZE := 48
const PIXEL_SIZE := 0.0065
const LAUNCH_HEIGHT := 0.6
const REST_HEIGHT_MIN := 0.3
const REST_HEIGHT_MAX := 2.6
const FLOOR_SEARCH_DEPTH := 6.0
const MONOSPACE_FONTS: PackedStringArray = ["Consolas", "Cascadia Mono", "Menlo", "SF Mono", "DejaVu Sans Mono", "Liberation Mono", "Courier New", "monospace"]
const COLORS: Array[Color] = [
	Color(1.0, 0.5, 0.1),
	Color(1.0, 0.3, 0.3),
	Color(1.0, 0.92, 0.25),
	Color(0.45, 1.0, 0.35),
	Color(0.35, 0.9, 1.0),
]
const SNIPPETS: Array[String] = [
	"let x = x.clone().clone().clone();",
	".unwrap().unwrap().unwrap()",
	"unsafe { /* trust me bro */ }",
	"fn main() { todo!() }",
	"#[allow(clippy::all)]",
	"Rc<RefCell<Arc<Mutex<Box<T>>>>>",
	"// TODO: fight the borrow checker",
	"std::mem::forget(ethics);",
	"loop { raise_series_b(); }",
	"match vibes { _ => panic!() }",
	"static mut GLOBAL: Vec<Vec<i32>>;",
	"if x == true == true {",
	"let _ = result; // ignore err lol",
	"as u8 as i64 as f32 as usize",
	".expect(\"should never happen\")",
	"&&&&&&&&&&&&&&str",
	"error[E0382]: use of moved value",
	"impl Drop for Runway { }",
	"unsafe { transmute(vibes) }",
	"'a: 'b + 'c + 'static",
	"fn is_even(n: i32) -> bool {\n    n == 0 || n == 2 || n == 4\n}",
	"use std::*;\nuse crate::*;\nuse super::*;",
	"let mut mut_mut = &mut &mut x;",
	"// generated by AI. do not read.",
	"Box::leak(Box::new(runway))",
	"warning: 1,337 unused variables",
	"cargo build --release\n   Compiling... (day 3)",
	".unwrap_or_else(|| unwrap())",
]

static var monospace_font: SystemFont

var velocity := Vector3.ZERO
var rest_y := 0.0
var age := 0.0
var has_landed := false


static func spawn_shower(parent: Node3D, origin: Vector3, line_count: int) -> void:
	var floor_y := find_floor_y(parent, origin)
	for line_index: int in line_count:
		var line := RustSlop.new()
		line.text = SNIPPETS[randi() % SNIPPETS.size()]
		line.modulate = COLORS[randi() % COLORS.size()]
		line.velocity = pick_launch_velocity()
		line.rest_y = floor_y + randf_range(REST_HEIGHT_MIN, REST_HEIGHT_MAX)
		parent.add_child(line)
		line.global_position = origin + Vector3.UP * LAUNCH_HEIGHT


static func find_floor_y(parent: Node3D, origin: Vector3) -> float:
	var ray_start := origin + Vector3.UP * 0.5
	var ray_end := origin + Vector3.DOWN * FLOOR_SEARCH_DEPTH
	var query := PhysicsRayQueryParameters3D.create(ray_start, ray_end, WORLD_LAYER)
	var hit := parent.get_world_3d().direct_space_state.intersect_ray(query)
	return origin.y if hit.is_empty() else hit["position"].y


static func pick_launch_velocity() -> Vector3:
	var angle := randf() * TAU
	var outward_speed := randf_range(3.5, 9.0)
	return Vector3(cos(angle) * outward_speed, randf_range(4.0, 8.0), sin(angle) * outward_speed)


static func get_monospace_font() -> SystemFont:
	if monospace_font == null:
		monospace_font = SystemFont.new()
		monospace_font.font_names = MONOSPACE_FONTS
	return monospace_font


func _ready() -> void:
	font = get_monospace_font()
	font_size = FONT_SIZE
	pixel_size = PIXEL_SIZE
	outline_size = 14
	outline_modulate = Color(0, 0, 0, 0.95)
	billboard = BaseMaterial3D.BILLBOARD_ENABLED
	shaded = false
	cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	double_sided = true
	horizontal_alignment = HORIZONTAL_ALIGNMENT_LEFT


func _process(delta: float) -> void:
	age += delta
	if not has_landed:
		fly(delta)
	fade_out_near_end()
	if age >= LIFETIME_SECONDS:
		queue_free()


func fly(delta: float) -> void:
	velocity.y -= GRAVITY * delta
	var drag := maxf(1.0 - AIR_DRAG * delta, 0.0)
	velocity.x *= drag
	velocity.z *= drag
	global_position += velocity * delta
	if velocity.y < 0.0 and global_position.y <= rest_y:
		global_position.y = rest_y
		has_landed = true


func fade_out_near_end() -> void:
	var fade_start := LIFETIME_SECONDS - FADE_SECONDS
	if age < fade_start:
		return
	var alpha := clampf(1.0 - (age - fade_start) / FADE_SECONDS, 0.0, 1.0)
	modulate.a = alpha
	outline_modulate.a = alpha * 0.95
